[tool.poetry]
name = "hello-world"
version = "0.1.0"
description = "Just a simple Hello-World module"
authors = ["tungtv"]
license = "N/A"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
